---
  dataSource: "milestones"
  prefix: ""
  ignoreLabels: 
    - "category: a11y :wheelchair:"
    - "category: assets :file_folder:"
    - "category: design tokens :nail_care:"
    - "category: documentation :notebook:"
    - "category: site :computer:"
    - "category: ui-kit :triangular_ruler:"
    - "component: accordion"
    - "component: alert"
    - "component: autocomplete"
    - "component: box"
    - "component: button"
    - "component: card"
    - "component: checkbox"
    - "component: chip"
    - "component: container"
    - "component: date-picker"
    - "component: dialog"
    - "component: dropdown"
    - "component: footer"
    - "component: form"
    - "component: header"
    - "component: heading"
    - "component: input-text"
    - "component: link"
    - "component: progress-bar"
    - "component: radio"
    - "component: select"
    - "component: sidenav"
    - "component: slider"
    - "component: spinner"
    - "type: enhancement :pencil2:"
    - "type: disparity :warning:"
    - "status: work in progress :+1:"
    - "status: under evaluation :mag_right:"
    - "task: story :white_check_mark:"
  groupBy: {"Documentation:": ["category: documentation :notebook:"], "UI-Kit:": ["category: ui-kit :triangular_ruler:"], "Fixes:": ["type: disparity :warning:"]} 
  milestoneMatch: "Release {{tag_name}}"
  changelogFilename: "CHANGELOG.md"
